name: travel_app
description: "An AI-powered travel application that helps users plan, explore, and enjoy trips more efficiently."

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core for Initialization
  firebase_core: ^2.25.4

  # Firebase Authentication
  firebase_auth: ^4.16.0

  # Firestore Database
  cloud_firestore: ^4.14.0

  # Google Sign-In
  google_sign_in: ^6.1.0

  # State Management
  provider: ^6.0.5

  # Cache
  shared_preferences: ^2.2.2

  # Localization
  intl: ^0.18.1
 
  flutter_localizations:
    sdk: flutter

  # JSON 
  json_annotation: ^4.8.1

  # Internet Connectivity
  connectivity_plus: ^6.0.3

  # AI
  google_generative_ai: ^0.4.6

  # Security
  flutter_dotenv: ^5.2.1

  # UI
  carousel_slider: ^5.0.0

  # Cupertino 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # JSON Serialization build runner
  build_runner: ^2.4.8

  # JSON Serialization
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/logo/
    - assets/images/
    - .env

